apiVersion: v2
name: stalwart-platform
description: Platform dependencies for Stalwart — provisions PostgreSQL, S3 blob storage, secrets, and observability
type: application
version: 0.1.0
appVersion: "v0.16.1"
maintainers:
  - name: 7k-hiroba
keywords:
  - platform
  - crossplane
  - cnpg
  - hiroba
  - mail
  - stalwart
home: https://github.com/7K-Hiroba/stalwart
sources:
  - https://github.com/7K-Hiroba/stalwart
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: documentation
      url: https://hiroba.7kgroup.org/docs/apps/stalwart/helm-platform
    - name: upstream
      url: https://github.com/stalwartlabs/stalwart
    - name: source
      url: https://github.com/7K-Hiroba/stalwart
    - name: support
      url: https://github.com/7K-Hiroba/stalwart/issues
  artifacthub.io/maintainers: |
    - name: 7k-hiroba
